apiVersion: v1
kind: Service
metadata:
  name: venus-messager-{{.UniqueId}}-service
spec:
  type: ClusterIP
  selector:
    app: venus-messager-{{.UniqueId}}-pod
  ports:
    - protocol: TCP
      port: 39812