apiVersion: v1
kind: Service
metadata:
  name: venus-market-client-{{.UniqueId}}-service
spec:
  type: ClusterIP
  selector:
    app: venus-market-client-{{.UniqueId}}-pod
  ports:
    - protocol: TCP
      port: 41231
      name: api
    - protocol: TCP
      port: 34123
      name: libp2p

