apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: venus-wallet-{{.UniqueId}}
spec:
  replicas: 1
  serviceName: venus-wallet-{{.UniqueId}}-svc
  selector:
    matchLabels:
      app: venus-wallet-{{.UniqueId}}-pod
  template:
    metadata:
      labels:
        app: venus-wallet-{{.UniqueId}}-pod
    spec:
      containers:
        - name: venus-wallet-{{.UniqueId}}
          image: "{{if gt (len .PrivateRegistry) 0}}{{.PrivateRegistry}}/{{end}}filvenus/venus-wallet:{{.CodeVersion}}"
          args: ["run"]
          ports:
            - containerPort: 5678
              protocol: TCP
          volumeMounts:
            - mountPath: /root
              name: venus-wallet-pvc
            - name: venus-wallet-vol
              mountPath: "/root/.venus_wallet/config.toml"
              subPath: "config.toml"
      volumes:
        - name: venus-wallet-vol
          configMap:
            name: venus-wallet-cfg-{{.UniqueId}}
            items:
              - key: config.toml
                path: config.toml
  volumeClaimTemplates:
    - metadata:
        name: venus-wallet-pvc # name+podname
        labels:
          app: venus-wallet-{{.UniqueId}}-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "nfs-client"
        resources:
          requests:
            storage: 100Mi