apiVersion: v1
kind: ConfigMap
metadata:
  name: damocles-manager-cfg-{{.UniqueId}}
data:
  sector-manager.cfg: |
    # Default config:
    [Common]
    [Common.API]
    Chain = "{{.NodeUrl}}"
    Messager = "{{.MessagerUrl}}"
    Market = "{{.MarketUrl}}"
    Gateway = ["{{.GatewayUrl}}"]
    Token = "{{.UserToken}}"
    #ChainEventInterval = "1m0s"
{{ range $index, $value := .PieceStores }}
    [[Common.PieceStores]]
    Name = "{{$value}}"
    Path = "/piece/{{$value}}"
    #Plugin = ""
    #PluginName = "s3store"
    [Common.PieceStores.Meta]
    #SomeKey = "SomeValue"
{{ end }}
{{ range $index, $value := .PersistStores }}
    [[Common.PersistStores]]
    Name = "{{$value}}"
    Path = "/persist/{{$value}}"
    Strict = false
    ReadOnly = false
    Weight = 0
    AllowMiners = []
    #DenyMiners = [3, 4]
    #Plugin = ""
    #PluginName = "s3store"
{{ end }}
    [Common.PersistStores.Meta]
    #SomeKey = "SomeValue"

    [Common.DB]
    Driver = "badger"
    [Common.DB.Badger]
    # BaseDir = ""

    [Common.Proving]
