apiVersion: v1
kind: ConfigMap
metadata:
  name: damocles-worker-cfg-{{.UniqueId}}
data:
{{- range $i := until 20 }}
  test{{$i}}: |
    - name: /mnt/mount/k8s/{{.miner}}/test{{$i}}
     path: /data/test{{$i}}
{{- end }}
  damocles-worker.toml: |
    [worker]
    name = "filedrive"
    rpc_server.host = "0.0.0.0"
    rpc_server.port = 17891
    local_pieces_dir = "/shared-dir/m-piece/piece"

    [sector_manager]
    rpc_client.addr = "{{.DamoclesManagerUrl}"
    rpc_client.headers = { User-Agent = "jsonrpc-core-client" }
    piece_token = "{{.MarketToken}}"
    [sealing]
    allowed_miners = [{{.MinerAddress}}]
    allowed_sizes = ["8MiB"]
    enable_deals = true
    disable_cc = false
    max_deals = 6
    min_deal_space = "2kiB"
    max_retries = 6

    [[sealing_thread]]
    location = "/shared-dir/{{.MinersAddress}}/test1"

    [[sealing_thread]]
    location = "/shared-dir/{{.MinersAddress}}/test2"

    [[sealing_thread]]
    location = "/shared-dir/{{.MinersAddress}}/test3"

    [[sealing_thread]]
    location = "/shared-dir/{{.MinersAddress}}/test4"

    [[sealing_thread]]
    location = "/shared-dir/{{.MinersAddress}}/test5"

    [[sealing_thread]]
    location = "/shared-dir/{{.MinersAddress}}/test6"

    [[sealing_thread]]
    location = "/shared-dir/{{.MinersAddress}}/test7"

    [[sealing_thread]]
    location = "/shared-dir/{{.MinersAddress}}/test8"
    plan = "snapup"

    [[sealing_thread]]
    location = "/shared-dir/{{.MinersAddress}}/test9"
    plan = "rebuild"

    [[sealing_thread]]
    location = "/shared-dir/{{.MinersAddress}}/test10"
    plan = "unseal"

    [[attached]]
    name = "storage"
    location = "/shared-dir/{{.TestID}}/{{.MinerAddress}}"
    [attached_selection]
    # enable_space_weighted = false

    [processors.limitation.concurrent]
    add_pieces = 10
    pc1 = 10
    pc2 = 1
    c2 = 1
    tree_d = 1
    snap_encode = 1
    snap_prove = 1

    [processors.static_tree_d]
    8MiB = "/shared-dir/filecoin-proof-parameters/tree_d_all_zero_8388608"

    [[processors.pc1]]
    concurrent = 10
    
    [[processors.pc2]]
    concurrent = 1
    
    [[processors.c2]]
    concurrent = 1
    
    [[processors.tree_d]]
    concurrent = 1

    [[processors.snap_encode]]
    concurrent = 1

    [[processors.snap_prove]]
    concurrent = 1