apiVersion: v1
kind: Service
metadata:
  name: venus-gateway-{{.UniqueId}}-service
spec:
  type: ClusterIP
  selector:
    app: venus-gateway-{{.UniqueId}}-pod
  ports:
    - protocol: TCP
      port: 45132