apiVersion: v1
kind: Service
metadata:
  name: {{plugin-name}}-{{.UniqueId}}-svc
spec:
  type: ClusterIP
  selector:
    app: {{plugin-name}}-{{.UniqueId}}-pod
  ports:
    - protocol: TCP
      port: {{api-port}}
      name: api
    - protocol: TCP
      port: {{libp2p-port}}
      name: libp2p
