apiVersion: v1
kind: Service
metadata:
  name: genesis-{{.UniqueId}}-svc
spec:
  clusterIP: None
  selector:
    app: genesis-{{.UniqueId}}-pod
  ports:
    - protocol: TCP
      port: 1234
      name: rpc
    - protocol: TCP
      port: 34567
      name: p2p
