apiVersion: apps/v1
kind: Deployment
metadata:
  name: venus-chain-co-{{.UniqueId}}
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      app: venus-chain-co-{{.UniqueId}}-pod
  template:
    metadata:
      labels:
        app: venus-chain-co-{{.UniqueId}}-pod
    spec:
      containers:
        - name: venus-chain-co-{{.UniqueId}}
          image: "{{if gt (len .PrivateRegistry) 0}}{{.PrivateRegistry}}/{{end}}filvenus/chain-co:{{.CodeVersion}}"
          args: ["run" {{if gt (len .Nodes) 0}}{{range $i, $a := .Nodes}},--node={{$a}}{{end}}{{end}}{{if gt (len .AuthUrl) 0}}, --auth-url={{.AuthUrl}}{{end}}]
          ports:
            - containerPort: 1234
              protocol: TCP