apiVersion: v1
kind: Service
metadata:
  name: venus-chain-co-{{.UniqueId}}-service
spec:
  type: ClusterIP
  selector:
    app: venus-chain-co-{{.UniqueId}}-pod
  ports:
    - protocol: TCP
      port: 1234