apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-nfs4
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage-nfs-4
  mountOptions:
    - lock
    - nfsvers=3
  nfs:
    path: /mnt/storage-nfs-4
    server: 192.168.200.35

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testnet-shared-dir
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: storage-nfs-4
