apiVersion: v1
kind: Pod
metadata:
  namespace: {{.NameSpace}}
  name: test-runner-{{.TestId}}
  labels:
    app: venus-testrunner-pod
    apptype: testrunner
    testid: {{.TestId}}
spec:
  restartPolicy: OnFailure
  initContainers:
  containers:
    - name: venus-testrunner
      image: "{{if gt (len .PrivateRegistry) 0}}{{.PrivateRegistry}}/{{end}}filvenus/testrunner:li"
      imagePullPolicy: Always
      args: [{{.Args}}]
      env:
        - name: PRODUCTION
          value: "true"
      volumeMounts:
        - mountPath: /shared-dir
          name: shared-dir-v
          subPath: {{.NameSpace}}
  volumes:
    - name: shared-dir-v
      persistentVolumeClaim:
        claimName: shared-dir