apiVersion: v1
kind: Pod
metadata:
  name: test-runner-{{.TestId}}
  labels:
    app: venus-testrunner-pod
    apptype: testrunner
    testid: {{.TestId}}
spec:
  initContainers:
  containers:
    - name: venus-testrunner
      image: "{{if gt (len .PrivateRegistry) 0}}{{.PrivateRegistry}}/{{end}}filvenus/testrunner:e57a212a573dc14f6e74fbea9ba56a42cf389ac9"
      imagePullPolicy: IfNotPresent
      args: ["--log-level=DEBUG","--config=/shared-dir/k8stest/config-template.toml", "--plugins=/shared-dir/k8stest/plugins", "--taskId={{.TaskID}}"]
      env:
        - name: PRODUCTION
          value: "true"
      volumeMounts:
        - mountPath: /shared-dir
          name: shared-dir-v
  volumes:git s
    - name: shared-dir-v
      persistentVolumeClaim:
        claimName: testnet-shared-dir