apiVersion: v1
kind: Pod
metadata:
  name: testrunner-debug
  labels:
    app: ubuntu
spec:
  containers:
  - image: "ubuntu:22.04"
    command: 
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: testrunner
    volumeMounts:
      - mountPath: /shared-dir
        name: shared-dir-v
        subPath: default
  restartPolicy: Always
  volumes:
  - name: shared-dir-v
    persistentVolumeClaim:
      claimName: shared-dir