apiVersion: v1
kind: Pod
metadata:
  name: testrunner-debug
  labels:
    app: ubuntu
spec:
  containers:
  - image: "192.168.200.175/filvenus/venus-buildenv:latest"
    command: 
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: testrunner
    volumeMounts:
      - mountPath: /shared-dir
        name: shared-dir-v
        subPath: li
  restartPolicy: Always
  volumes:
  - name: shared-dir-v
    persistentVolumeClaim:
      claimName: shared-dir