apiVersion: v1
kind: Service
metadata:
  name: venus-market-{{.UniqueId}}-service
spec:
  type: ClusterIP
  selector:
    app: venus-market-{{.UniqueId}}-pod
  ports:
    - protocol: TCP
      port: 41235
      name: api
    - protocol: TCP
      port: 58418
      name: libp2p

