apiVersion: apps/v1
kind: Deployment
metadata:
  name: venus-auth-{{.UniqueId}}
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      app: venus-auth-{{.UniqueId}}-pod
  template:
    metadata:
      labels:
        app: venus-auth-{{.UniqueId}}-pod
    spec:
      containers:
        - name: venus-auth-{{.UniqueId}}
          image: "{{if gt (len .PrivateRegistry) 0}}{{.PrivateRegistry}}/{{end}}filvenus/venus-auth:{{.CodeVersion}}"
          args:
            - "run"
          ports:
            - containerPort: 8989
              protocol: TCP
          volumeMounts:
            - mountPath: /shared-dir
              name: shared-dir-v
      volumes:
        - name: shared-dir-v
          persistentVolumeClaim:
            claimName: testnet-shared-dir
        - name: pod-logs
          hostPath:
            path: /var/log/pods/{{.Release.Namespace}}_{{.Release.Name}}_{{.Name}}_{{.PodUID}}
            type: Directory
      initContainers:
        - name: copy-logs
          image: busybox
          command: ["sh", "-c", "cp -R /var/log/pods/* /shared-dir/"]
          volumeMounts:
            - name: shared-dir-v
              mountPath: "/shared-dir"
            - name: pod-logs
              mountPath: "/var/log/pods"
          securityContext:
            privileged: true
      securityContext:
        fsGroup: 1000
