apiVersion: apps/v1
kind: Deployment
metadata:
  name: venus-auth-{{.UniqueId}}
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      app: venus-auth-{{.UniqueId}}-pod
  template:
    metadata:
      labels:
        app: venus-auth-{{.UniqueId}}-pod
    spec:
      containers:
        - name: venus-auth-{{.UniqueId}}
          image: "{{if gt (len .PrivateRegistry) 0}}{{.PrivateRegistry}}/{{end}}filvenus/venus-auth:{{.CodeVersion}}"
          args:
            - "run"
            - "--log-file=/shared-dir-v/k8slog/venus-auth-{{.UniqueId}}.log"
          ports:
            - containerPort: 8989
              protocol: TCP
          volumeMounts:
            - mountPath: /shared-dir
              name: shared-dir-v
      volumes:
        - name: shared-dir-v
          persistentVolumeClaim:
            claimName: testnet-shared-dir
