apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: venus-auth-{{.UniqueId}}
spec:
  replicas: {{.Replicas}}
  serviceName: venus-auth-{{.UniqueId}}-svc
  selector:
    matchLabels:
      app: venus-auth-{{.UniqueId}}-pod
  template:
    metadata:
      labels:
        app: venus-auth-{{.UniqueId}}-pod
    spec:
      containers:
        - name: venus-auth-{{.UniqueId}}
          image: "{{if gt (len .PrivateRegistry) 0}}{{.PrivateRegistry}}/{{end}}filvenus/venus-auth:{{.CodeVersion}}"
          args: ["run", "--db-type", "mysql", "--mysql-dsn", "{{.MysqlDSN}}"]
          ports:
            - containerPort: 8989
              protocol: TCP
          volumeMounts:
            - mountPath: /root
              name: venus-auth-ha-pvc
  volumeClaimTemplates:
    - metadata:
        name: venus-auth-ha-pvc # name+podname
        labels:
          app: venus-auth-ha-{{.UniqueId}}-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "nfs-client"
        resources:
          requests:
            storage: 100Mi





