apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: venus-sector-manager-{{.UniqueId}}
spec:
  replicas: 1
  serviceName: venus-sector-manager-{{.UniqueId}}-svc
  selector:
    matchLabels:
      app: venus-sector-manager-{{.UniqueId}}-pod
  template:
    metadata:
      labels:
        app: venus-sector-manager-{{.UniqueId}}-pod
    spec:
      initContainers:
        - name: init-myservice
          image: {{if gt (len .PrivateRegistry) 0}}{{.PrivateRegistry}}/{{end}}library/busybox:1.35
          command: ['sh', '-c', "mkdir -p /root/.venus-sector-manager; cp /root/sector-manager.tmp /root/.venus-sector-manager/sector-manager.cfg"]
          volumeMounts:
            - mountPath: /root
              name: venus-messager-receive-pvc
            - name: sector-manager-cfg
              mountPath: "/root/sector-manager.tmp"
              subPath: "sector-manager.cfg"
            - mountPath: /shared-dir
              name: shared-dir-v
              subPath: {{.NameSpace}}
      containers:
        - name: venus-sector-manager-{{.UniqueId}}
          image: "{{if gt (len .PrivateRegistry) 0}}{{.PrivateRegistry}}/{{end}}filvenus/venus-sector-manager:{{.CodeVersion}}"
          args: ["run"]
          ports:
            - containerPort: 1789
              protocol: TCP
          volumeMounts:
            - mountPath: /root
              name: venus-messager-receive-pvc
            - name: sector-manager-cfg
              mountPath: "/root/sector-manager.tmp"
              subPath: "sector-manager.cfg"
            - mountPath: /shared-dir
              name: shared-dir-v
              subPath: {{.NameSpace}}
      volumes:
        - name: sector-manager-cfg
          configMap:
            name: venus-sector-manager-cfg-{{.UniqueId}}
            items:
              - key: sector-manager.cfg
                path: sector-manager.cfg
        - name: shared-dir-v
            persistentVolumeClaim:
              claimName: shared-dir
  volumeClaimTemplates:
    - metadata:
        name: venus-messager-receive-pvc # name+podname
        labels:
          app: venus-messager-receive-{{.UniqueId}}-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "nfs-client"
        resources:
          requests:
            storage: 300Mi