apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-dir-production
  namespace: production
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "shared-dir-production"
  mountOptions:
    - lock
    - nfsvers=3
  nfs:
    path: /mnt/storage-nfs-4
    server: 192.168.200.35

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  shared-dir
  namespace: production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: shared-dir-production